### ISSUE TITLE
[Suggestions] Various UI Improvements

### ISSUE THREAD

**Issue by GoblinGuide** [PunishXIV/AutoHook#20]
Bluntly, if I was in charge I would immediately revert AutoHook to the previous version and spend some time thinking about how I wanted the UI to look a year from now.

Adding one button for every single option and multiple dropdowns means that I'm overwhelmed just trying to find the options I want, let alone configuring them. This isn't sustainable. It feels like 95% of fishing case functionality was already there, but now it's "too many cooks ruin the UI design stew". The most common question in the Discord channel seems to be "how do I make AH auto cast". How do you square that with this absolutely gauntlet of nested menus?

However, that's just me ranting, and not constructive, so here are my specific suggestions:

Cascading menus are awful. There are literally four distinct options hiding in a dropdown inside a dropdown inside a dropdown inside a dropdown... times three, because that's "per fish bite"
![image](https://github.com/PunishXIV/AutoHook/assets/12886590/e010323e-7522-48ef-b0bd-232c8c7a637d)

Previous version: Hook timer configuration took one click. This click was just to just open the first dropdown with no purpose (see the next point below), so in general it took 0 clicks to get to.

Current version: I want to set a single minimum and maximum time to hook literally any fish of any bite type. It now takes me three clicks, at which point I get to this:
![image](https://github.com/PunishXIV/AutoHook/assets/12886590/fec18b26-f26d-40d8-9ffa-186d2071800a)
to configure _one of the three distinct types of bite_.

A single global hook minimum/maximum timer should be visible **within one click**. That's one of the most basic things you can do while fishing, and it works just fine as a "lazy" timer to only hook one specific type of bite when only that bite is enabled.

Let's try to set one! First, click "Timeout"
![image](https://github.com/PunishXIV/AutoHook/assets/12886590/f555f67f-84e6-4f95-9591-e234eeb39900)

and then click... oops! There's a maximum time here, but no minimum time here! So scroll back up, click twice more to set a hooking timer on !, twice more to set a hooking timer on !!, twice more to set a hooking timer on !!!, and any time you want to edit that time you get to repeat **six clicks and three numeric entry fields**.

Honest question: did anyone test this before it was released? Were they able to figure it out? Is it really just me?

And that's leaving aside that there's **an entire second set of timers** right below the first set of timers:
![image](https://github.com/PunishXIV/AutoHook/assets/12886590/af6e5cf1-cff3-4683-9090-544d1233581b)
I don't even know what "Use Mooch Timer" would ever do here. This is the Bait tab and not the Mooch tab, so why is there a "mooch timer" option? This shouldn't be controlling the time for hooking a Mooch, because we have a Mooch tab for that. What does this even do?

I thought maybe I was missing a config option, so I went to Config and messed around with every possible combination of this setting:
![image](https://github.com/PunishXIV/AutoHook/assets/12886590/5d7dd1b1-1b93-4e15-bbfb-a151be0a77d1)

As a consequence, I managed to make it _even worse_:
![image](https://github.com/PunishXIV/AutoHook/assets/12886590/bfb79256-514a-4910-9982-b6891e8e26af)
![image](https://github.com/PunishXIV/AutoHook/assets/12886590/eb682c39-1661-4a2b-8206-05208f33b11b)

Those windows need a minimum distance between each other, rather than spawning on top of each other like that. Using "Type 1" instead of "Type 2" band-aids the problem by having the button be large because it says the word "Configure", but you end up with the same issue:
![image](https://github.com/PunishXIV/AutoHook/assets/12886590/6c7afca5-c39d-47e7-898c-22f499dfe60a)

Now I'll get off my soapbox. You get what I'm saying and why I'm angry. AutoHook was great last week and now - though it's added a feature I've been wanting for at least a month - I'm literally not going to use it at any point until it's changed again. Please.

Here's some (hopefully quick and easy) small suggestions too:
1) The top "All Baits"/"All Mooches" bars shouldn't exist in the global preset. They're a dropdown with no purpose:
![image](https://github.com/PunishXIV/AutoHook/assets/12886590/cae728f7-fc86-4911-bc1a-79089b65048b)
This shouldn't be something that a user ever sees by accident if they click in the wrong place. I assume your hands are somehow tied by ImGui or whatever, I'm really just an ideas guy here and I do apologize for that.

2) You already know about removing Powerful hookset from ! and Precision from !! but I'm putting it here anyway to have it in writing.
![image](https://github.com/PunishXIV/AutoHook/assets/12886590/b3913c13-5d8f-4787-8194-8e4903e992a2)

3) The language dropdown is important and should definitely be up top, but it should be literally anywhere _other_ than next to the Changelog, because that is the only position that might make someone think "oh, this gives the language for the Changelog". And by someone, I mean me. Perhaps left-align it? And then you could put the "Current Status Header" between the two, make that one bar instead of two, you get what I mean, might not fit always though depending on how it's formatted, with with me here.
![image](https://github.com/PunishXIV/AutoHook/assets/12886590/07697306-29f5-4d8e-8918-fc56a3c63401)

4) The most important option should always go at the top. Move "Auto Cast only at specific times (Eorzea Time)" over to the "Extra" tab, because there's no way in hell it's getting used often enough to take up this precious real estate.
![image](https://github.com/PunishXIV/AutoHook/assets/12886590/5f1f6c24-b753-4e26-a994-b2f1b2245dea)

5) If there's only the one guide to using YesAlready to accept collectibles, you don't need a Guides tab. Just move that button under the Config options and remove the "configs/guides" tabs to save a click.

(And thank you for reading all this. I know I probably come off like a real jerk.)

**Comment by GoblinGuide** [comment]
(I assume much of this is resolved by chika's update that I didn't know existed. But if any of it isn't, feel free to steal whatever's actually useful from my rude rant!)

**Comment by InitialDet** [comment]
Thank you for the feedback
