### ISSUE TITLE
remove "enable auto casts"

### ISSUE THREAD

**Issue by Jaksuhn** [PunishXIV/AutoHook#9]
seems to be a redundant option with no use case, and can potentially cause confusion with "auto cast line" for newcomers

**Comment by github-1348A55** [comment]
I can relate to this.

What I personally feel is something else,
I'm wondering why "default presets" and "custom presets" are separate tabs and independent of each other.

These should be combined and placed in one tab.
The first one in the drop-down list is the default preset,
If the second and subsequent drop-down lists are custom presets added by the user.
There will be little confusion for users.

**Comment by awgil** [comment]
Tbh i find it useful - it allows quickly disabling the whole feature (eg when i'm doing prep and it's not worth setting up a preset for that).

I think it's quite obvious that upper checkbox enables/disables whole feature, and checkbox on a step disables individual step?

**Comment by InitialDet** [comment]
Theres no reason to remove it, its better to have it instead of having to uncheck every other option one by one if you want to turn everything off for a moment.
